### ISSUE TITLE
why is the generated images so bad?

### ISSUE THREAD

**Issue by zh-ding** [yookoon/VLAE#2]
![image](https://user-images.githubusercontent.com/24126173/61320612-952eae00-a7be-11e9-8328-cb85eb05c312.png)

**Comment by yookoon** [comment]
Will you try smaller latent variable dimensions? (e.x. 16)

We have experienced similar issues when the latent variable dimension gets large on Gaussian output models. We hypothesize that it happens when the latent variable dimension exceeds the intrinsic data manifold dimension, so that some latent dimensions fit to noise dimensions of data. 

Or you can use Bernoulli output models, which are free from such artifacts.

**Comment by zh-ding** [comment]
yeah, been better, but still much worse than the vanilla vae

**Comment by yookoon** [comment]
It will be helpful if you provide more details. Else, I will close this issue.

**Comment by zh-ding** [comment]
yeah thanks for your reply. I've changed the z-dim smaller to 20 as you said before, but the generated results are still not good as vanilla vae.
Maybe I've misunderstood your paper, but from my perspective, you are trying to use local linearity to fit global non-linearity?

**Comment by yookoon** [comment]
If you worry about the visual generation quality on MNIST, I suggest you use Bernoulli output models. 

I'm not sure what you mean by global non-linearity, but the gist of our work is that we use local linearity of ReLU networks to get a better posterior approximation for latent variable models. Of course, the data manifold will be non-linear in general, so we are modeling the nonlinear manifold with a piece-wise linear one.

**Comment by zh-ding** [comment]
Oh I see, very appreciate for your help.
